tipos:
    path:     /
    defaults: { _controller: "uniVideojuegosBundle:tipos:index" }

tipos_show:
    path:     /{id}/show
    defaults: { _controller: "uniVideojuegosBundle:tipos:show" }

tipos_new:
    path:     /new
    defaults: { _controller: "uniVideojuegosBundle:tipos:new" }

tipos_create:
    path:     /create
    defaults: { _controller: "uniVideojuegosBundle:tipos:create" }
    requirements: { _method: post }

tipos_edit:
    path:     /{id}/edit
    defaults: { _controller: "uniVideojuegosBundle:tipos:edit" }

tipos_update:
    path:     /{id}/update
    defaults: { _controller: "uniVideojuegosBundle:tipos:update" }
    requirements: { _method: post|put }

tipos_delete:
    path:     /{id}/delete
    defaults: { _controller: "uniVideojuegosBundle:tipos:delete" }
    requirements: { _method: post|delete }
  
tipos_buscar_tipos:
    path:     /buscartipos
    defaults: { _controller: "uniVideojuegosBundle:tipos:buscarTipos" }

tipos_responder_tipos:
    path:     /respondertipos
    defaults: { _controller: "uniVideojuegosBundle:tipos:responderTipos" }
    requirements: { _method: post|put }
